CPU = 1
RAM = 1024
BOX_NAME = "ubuntu/xenial64"

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = RAM
    v.cpus = CPU
  end

  # Configure load balancer
  config.vm.define "lb" do |lb|
    lb.vm.box = BOX_NAME
   # lb.vm.hostname = "lb"
    lb.vm.network "private_network", ip: "192.168.56.3"
  end

  # Configure web1
  config.vm.define "web1" do |web1|
    web1.vm.box = BOX_NAME
   # web1.vm.hostname = "web1"
    web1.vm.network "private_network", ip: "192.168.56.4"
  end

  # Configure web2
  config.vm.define "web2" do |web2|
    web2.vm.box = BOX_NAME
   # web2.vm.hostname = "web2"
    web2.vm.network "private_network", ip: "192.168.56.5"
  end
end
