CPU=2
RAM=2048
IP = "192.168.56.2"
Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.network "private_network", ip: IP
  config.vm.provider "virtualbox" do |v|
    v.memory = RAM
    v.cpus = CPU
  end

end
